#!/bin/bash
if [ $# -lt 4 ]; then
  echo "Use: range_hobo startdate enddate fid hobo_logger_id hobo_uid "
  exit
fi
 
startdate=$1
enddate=42
fid=$3 # 6915
logger=$4
uid=$5 # 7451
cd /var/www/d.live

sdate="$startdate 00:00:00"
edate="$enddate 23:59:59"
echo "Rscript modules/dh_weather/src/r/get_hobo_ts.R $fid dh_feature $uid $logger \"$sdate\" \"$edate\" /tmp/dh_weather_${fid}.txt"
Rscript modules/dh_weather/src/r/get_hobo_ts.R $fid dh_feature $uid $logger "$sdate" "$edate" /tmp/dh_weather_${fid}.txt
counter=$((counter + 1))
# now import to drupal
drush scr modules/dh_weather/src/set_timeseries_weather.php file /tmp/dh_weather_${fid}.txt
# do the end of day summary for this date 
drush scr modules/dh_weather/src/summarize_single_date.php dh_feature $fid $startdate
drush scr modules/dh_weather/src/summarize_single_date.php dh_feature $fid $enddate
# now ask for the last day summary, assuming the process is complete
drush scr modules/dh_weather/src/summarise_last24.php dh_feature ${fid}